import { WellnessActivity, RiskLevel, WellnessBadge, WellnessReward, WellnessTier } from '@/types/wellness';

export const WELLNESS_ACTIVITIES: Record<RiskLevel, WellnessActivity[]> = {
  minimal: [
    {
      id: 'minimal_gratitude_journaling',
      title: 'Gratitude Journaling',
      description: 'Take 5-10 minutes each day to write down three to five specific things you are genuinely grateful for. This exercise trains your brain to notice and focus on positive experiences, which can significantly improve your mood.',
      points: 10,
      riskLevel: 'minimal',
      category: 'mood',
      duration: 8,
    },
    {
      id: 'minimal_mindful_breathing',
      title: 'Mindful Breathing',
      description: 'A simple, 2-5 minute exercise to anchor yourself in the present moment. Sit comfortably, close your eyes, and focus all your attention on your breath. This practice helps calm the nervous system and reduces racing thoughts.',
      points: 5,
      riskLevel: 'minimal',
      category: 'mindfulness',
      duration: 4,
    },
    {
      id: 'minimal_social_connection',
      title: 'Scheduled Social Connection',
      description: 'Proactively schedule a meaningful interaction with someone you care about, such as a dedicated phone call, video chat, or a short walk. Strong social ties are fundamental to good mental health.',
      points: 15,
      riskLevel: 'minimal',
      category: 'social',
      duration: 20,
    },
    {
      id: 'minimal_hobby_flow',
      title: 'Engage in a Hobby (Flow State)',
      description: 'Dedicate at least 30 minutes to a hobby you enjoy, particularly one that fully absorbs your attention (like drawing, playing an instrument, or gardening). This is a powerful way to de-stress and boosts feelings of accomplishment.',
      points: 15,
      riskLevel: 'minimal',
      category: 'goal',
      duration: 30,
    },
    {
      id: 'minimal_positive_affirmations',
      title: 'Positive Affirmations',
      description: 'Start your day by saying or writing three positive statements about yourself or your day, such as "I am capable of handling today\'s challenges." This practice helps to challenge negative self-talk and sets an optimistic tone.',
      points: 5,
      riskLevel: 'minimal',
      category: 'mood',
      duration: 3,
    },
  ],
  mild: [
    {
      id: 'mild_grounding_technique',
      title: 'The 5-4-3-2-1 Grounding Technique',
      description: 'When you feel your thoughts spiraling, use your senses to ground yourself. Notice and name 5 things you can see, 4 things you can feel, 3 things you can hear, 2 things you can smell, and 1 thing you can taste.',
      points: 20,
      riskLevel: 'mild',
      category: 'mindfulness',
      duration: 8,
    },
    {
      id: 'mild_worry_time',
      title: '\'Worry Time\' Technique',
      description: 'Schedule a specific 15-minute "worry period." When a worry comes up outside this time, write it down and promise to address it only during the scheduled time. This technique helps contain anxious thoughts.',
      points: 25,
      riskLevel: 'mild',
      category: 'mindfulness',
      duration: 15,
    },
    {
      id: 'mild_problem_solving',
      title: 'Problem-Solving Breakdown',
      description: 'Choose one thing that is overwhelming you and break it down into the smallest possible steps. This makes large tasks feel less daunting and gives you a clear, actionable plan.',
      points: 20,
      riskLevel: 'mild',
      category: 'goal',
      duration: 15,
    },
    {
      id: 'mild_mindful_walking',
      title: 'Mindful Walking',
      description: 'Take a 15-minute walk, focusing only on your surroundings and bodily sensations (feet on the ground, rhythm of your breath) without music or podcasts. This combines the benefits of light exercise and mindfulness.',
      points: 15,
      riskLevel: 'mild',
      category: 'mindfulness',
      duration: 15,
    },
    {
      id: 'mild_feel_good_playlist',
      title: 'Create a \'Feel-Good\' Playlist',
      description: 'Curate a playlist of songs that you know lift your spirits, energize you, or make you feel calm. Music has a direct effect on mood, and having this tool ready can be very helpful.',
      points: 10,
      riskLevel: 'mild',
      category: 'mood',
      duration: 20,
    },
  ],
  moderate: [
    {
      id: 'moderate_cognitive_reframing',
      title: 'Cognitive Reframing: The Three C\'s',
      description: 'Use this CBT technique to challenge negative thoughts. Catch the thought, Check it for evidence and distortions, and Change it to be more balanced and realistic.',
      points: 40,
      riskLevel: 'moderate',
      category: 'education',
      duration: 20,
    },
    {
      id: 'moderate_daily_routine',
      title: 'Create a Structured Daily Routine',
      description: 'Create and write down a simple, consistent daily schedule that includes specific times for waking up, meals, study, relaxation, and sleep. A predictable routine provides a sense of stability and control.',
      points: 35,
      riskLevel: 'moderate',
      category: 'goal',
      duration: 30,
    },
    {
      id: 'moderate_sleep_hygiene',
      title: 'Sleep Hygiene Improvement',
      description: 'Take concrete steps to improve your sleep. This includes avoiding screens for an hour before bed, ensuring your room is dark and cool, and avoiding caffeine late in the evening.',
      points: 30,
      riskLevel: 'moderate',
      category: 'goal',
      duration: 25,
    },
    {
      id: 'moderate_professional_checkin',
      title: 'Schedule a Professional Check-in',
      description: 'This is the crucial step of booking an appointment with a school counselor, therapist, or doctor to discuss your mental health. Reaching out for professional help is a proactive and effective step towards feeling better.',
      points: 50,
      riskLevel: 'moderate',
      category: 'crisis',
      duration: 15,
    },
    {
      id: 'moderate_self_compassion',
      title: 'Self-Compassion Break',
      description: 'When you are feeling self-critical, take a 5-minute break. Acknowledge your suffering with kindness, reminding yourself that suffering is a part of life and that you can be kind to yourself in this moment.',
      points: 25,
      riskLevel: 'moderate',
      category: 'mindfulness',
      duration: 5,
    },
  ],
  severe: [
    {
      id: 'severe_crisis_helpline',
      title: 'Immediately Contact a Crisis Helpline',
      description: 'This is the most critical and immediate action. Your safety is the priority. Contact a professional who is available 24/7. Tele-MANAS (National Helpline): 14416, State Health Helpline (Tamil Nadu): 104',
      points: 100,
      riskLevel: 'severe',
      category: 'crisis',
      duration: 0,
    },
    {
      id: 'severe_safety_plan',
      title: 'Create a Safety Plan (With a Trusted Person)',
      description: 'A safety plan is a guide to help you get through moments of crisis. It must be created with a trusted adult (a parent, counselor, or doctor) and should list your warning signs, coping strategies, and support contacts.',
      points: 80,
      riskLevel: 'severe',
      category: 'crisis',
      duration: 30,
    },
    {
      id: 'severe_secure_environment',
      title: 'Remove or Secure Potential Means of Harm',
      description: 'A vital step in ensuring immediate safety is to make your environment safer by removing any objects that could be used for self-harm. Ask someone you trust for help with this step.',
      points: 75,
      riskLevel: 'severe',
      category: 'crisis',
      duration: 10,
    },
    {
      id: 'severe_trusted_person',
      title: 'Reach Out to a Trusted Person and Stay with Them',
      description: 'Do not be alone. Call a trusted family member or friend and ask them to be with you, either in person or on the phone, until you can get professional help. The goal is to stay connected and supported.',
      points: 75,
      riskLevel: 'severe',
      category: 'social',
      duration: 0,
    },
    {
      id: 'severe_safe_place',
      title: 'Go to a Safe Place',
      description: 'If your current environment feels unsafe, go to a place where you feel more secure. This could be a hospital emergency room, a trusted friend\'s house, or a community health center.',
      points: 75,
      riskLevel: 'severe',
      category: 'crisis',
      duration: 0,
    },
  ],
};

export const LEVEL_THRESHOLDS = [0, 100, 250, 500, 1000, 1500, 2500, 4000, 6000, 9000, 12000, 15000, 20000];

export const CATEGORY_COLORS = {
  mood: '#FF6B6B',
  mindfulness: '#4ECDC4',
  social: '#45B7D1',
  education: '#96CEB4',
  crisis: '#FF8A80',
  goal: '#FFD93D',
};

export const CATEGORY_ICONS = {
  mood: 'heart',
  mindfulness: 'brain',
  social: 'users',
  education: 'book-open',
  crisis: 'shield-alert',
  goal: 'target',
};

export const RISK_LEVEL_COLORS = {
  minimal: '#4CAF50',
  mild: '#FF9800',
  moderate: '#FF5722',
  severe: '#F44336',
};

export const WELLNESS_QUOTES = [
  "Every small step towards wellness counts.",
  "Your mental health journey is unique and valuable.",
  "Progress, not perfection, is the goal.",
  "You have the strength to overcome challenges.",
  "Taking care of yourself is not selfish, it's necessary.",
  "Each day is a new opportunity for growth.",
  "Your feelings are valid and important.",
  "Healing is not linear, and that's okay.",
];

export const TIER_THRESHOLDS: Record<WellnessTier, number> = {
  bronze: 0,
  silver: 250,
  gold: 500,
  platinum: 800,
};

export const TIER_NAMES: Record<WellnessTier, string> = {
  bronze: 'Seeker',
  silver: 'Explorer', 
  gold: 'Navigator',
  platinum: 'Mentor',
};

export const TIER_COLORS: Record<WellnessTier, string> = {
  bronze: '#CD7F32',
  silver: '#C0C0C0',
  gold: '#FFD700',
  platinum: '#E5E4E2',
};

export const WELLNESS_BADGES: WellnessBadge[] = [
  // Streak Badges
  {
    id: 'streak_7',
    title: '7-Day Mindfulness Streak',
    description: 'Complete activities for 7 consecutive days',
    icon: 'flame',
    type: 'streak',
    requirement: { type: 'streak', value: 7 },
    points: 50,
    tier: 'bronze',
  },
  {
    id: 'streak_30',
    title: '30-Day Journaling Habit',
    description: 'Complete activities for 30 consecutive days',
    icon: 'flame',
    type: 'streak',
    requirement: { type: 'streak', value: 30 },
    points: 200,
    tier: 'silver',
  },
  {
    id: 'streak_100',
    title: 'Wellness Champion',
    description: 'Complete activities for 100 consecutive days',
    icon: 'flame',
    type: 'streak',
    requirement: { type: 'streak', value: 100 },
    points: 500,
    tier: 'gold',
  },
  // Discovery Badges
  {
    id: 'anxiety_explorer',
    title: 'Anxiety Toolkit Explorer',
    description: 'Complete 5 mindfulness activities',
    icon: 'brain',
    type: 'discovery',
    requirement: { type: 'category', value: 5, category: 'mindfulness' },
    points: 75,
    tier: 'bronze',
  },
  {
    id: 'social_connector',
    title: 'Social Wellness Champion',
    description: 'Complete 10 social connection activities',
    icon: 'users',
    type: 'discovery',
    requirement: { type: 'category', value: 10, category: 'social' },
    points: 100,
    tier: 'silver',
  },
  {
    id: 'mood_master',
    title: 'Mood Tracking Master',
    description: 'Complete 20 mood-related activities',
    icon: 'heart',
    type: 'discovery',
    requirement: { type: 'category', value: 20, category: 'mood' },
    points: 150,
    tier: 'gold',
  },
  // Milestone Badges
  {
    id: 'minutes_100',
    title: 'Completed 100 Wellness Minutes',
    description: 'Spend 100 minutes on wellness activities',
    icon: 'clock',
    type: 'milestone',
    requirement: { type: 'points', value: 100 },
    points: 100,
    tier: 'bronze',
  },
  {
    id: 'points_1000',
    title: 'Wellness Warrior',
    description: 'Earn 1000 wellness points',
    icon: 'trophy',
    type: 'milestone',
    requirement: { type: 'points', value: 1000 },
    points: 200,
    tier: 'silver',
  },
  {
    id: 'activities_50',
    title: 'Activity Champion',
    description: 'Complete 50 wellness activities',
    icon: 'target',
    type: 'milestone',
    requirement: { type: 'activities', value: 50 },
    points: 250,
    tier: 'gold',
  },
  // Achievement Badges
  {
    id: 'early_bird',
    title: 'Early Bird',
    description: 'Complete activities in the morning for 7 days',
    icon: 'sunrise',
    type: 'achievement',
    requirement: { type: 'days', value: 7 },
    points: 75,
    tier: 'bronze',
  },
  {
    id: 'consistency_king',
    title: 'Consistency Champion',
    description: 'Complete at least one activity every day for a month',
    icon: 'calendar',
    type: 'achievement',
    requirement: { type: 'days', value: 30 },
    points: 300,
    tier: 'platinum',
  },
];

export const WELLNESS_REWARDS: WellnessReward[] = [
  // Bronze Tier Rewards
  {
    id: 'meditation_basic',
    title: 'Basic Meditation Sessions',
    description: 'Unlock 5 guided meditation sessions',
    type: 'content',
    cost: 100,
    tier: 'bronze',
    unlocked: false,
    category: 'mindfulness',
  },
  {
    id: 'theme_nature',
    title: 'Nature Theme',
    description: 'Calming nature-inspired app theme',
    type: 'theme',
    cost: 150,
    tier: 'bronze',
    unlocked: false,
  },
  // Silver Tier Rewards
  {
    id: 'meditation_advanced',
    title: 'Advanced Meditation Library',
    description: 'Access to 20+ advanced meditation sessions',
    type: 'content',
    cost: 300,
    tier: 'silver',
    unlocked: false,
    category: 'mindfulness',
  },
  {
    id: 'stress_workshop',
    title: 'Stress Management Workshop',
    description: 'In-depth video workshop on stress management',
    type: 'content',
    cost: 400,
    tier: 'silver',
    unlocked: false,
    category: 'education',
  },
  {
    id: 'theme_ocean',
    title: 'Ocean Sounds Theme',
    description: 'Relaxing ocean sounds and blue theme',
    type: 'theme',
    cost: 250,
    tier: 'silver',
    unlocked: false,
  },
  // Gold Tier Rewards
  {
    id: 'anxiety_masterclass',
    title: 'Anxiety Management Masterclass',
    description: 'Comprehensive course on managing anxiety',
    type: 'content',
    cost: 600,
    tier: 'gold',
    unlocked: false,
    category: 'education',
  },
  {
    id: 'speaking_workshop',
    title: 'Public Speaking Confidence',
    description: 'Workshop to overcome public speaking anxiety',
    type: 'content',
    cost: 700,
    tier: 'gold',
    unlocked: false,
    category: 'education',
  },
  {
    id: 'theme_premium',
    title: 'Premium Theme Collection',
    description: 'Access to all premium themes and sounds',
    type: 'theme',
    cost: 500,
    tier: 'gold',
    unlocked: false,
  },
  // Platinum Tier Rewards
  {
    id: 'peer_mentor',
    title: 'Peer Mentor Access',
    description: 'Unlock ability to help others in peer forum',
    type: 'feature',
    cost: 1000,
    tier: 'platinum',
    unlocked: false,
  },
  {
    id: 'personal_coach',
    title: 'Personal Wellness Coach',
    description: 'AI-powered personal wellness coaching',
    type: 'feature',
    cost: 1200,
    tier: 'platinum',
    unlocked: false,
  },
];